// create a json with random words that are not in the alphabet
export const complexWords = {
  carro: "carro",
  casa: "casa",
  perro: "perro",
  gato: "gato",
  calle: "calle",
  callejon: "callejon",
  manzana: "manzana",
  pera: "pera",
  mango: "mango",
  papaya: "papaya",
  platano: "platano",
  sandia: "sandia",
  melon: "melon",
  naranja: "naranja",
  limon: "limon",
  lima: "lima",
  uva: "uva",
  fresa: "fresa",
  cereza: "cereza",
  arandano: "arandano",
  frambuesa: "frambuesa",
  mora: "mora",
  ciruela: "ciruela",
  durazno: "durazno",
  mani: "mani",
  laptop: "laptop",
  computadora: "computadora",
  celular: "celular",
  telefono: "telefono",
  television: "television",
  radio: "radio",
  camioneta: "camioneta",
  camion: "camion",
  carroza: "carroza",
};

